version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias"
      - apt-get update && apt-get install -y ssh # Instalar SSH si no está disponible

  post_build:
    commands:
      - echo "Desplegando frontend a EC2"
      - ssh -o StrictHostKeyChecking=no -i /path/to/your/key.pem ubuntu@<tu-ip-o-dominio> "sudo rm -rf /var/www/html/* && sudo cp -r /codebuild/output/src1234567890/frontend/* /var/www/html/ && sudo systemctl restart nginx"

artifacts:
  files:
    - '*/'
  base-directory: frontend  # Este es el directorio donde se encuentran los archivos a desplegar
